name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Api
      run: git clone --depth 1 https://github.com/libxposed/api.git libxposed/api
            cd libxposed/api
            ./gradlew :api:publishApiPublicationToMavenLocal

    - name: Install Service
      run: git clone --depth 1 https://github.com/libxposed/service.git libxposed/service
            cd ../service
           ./gradlew :interface:publishInterfacePublicationToMavenLocal

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
