name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Checkout libxposed/api
      uses: actions/checkout@v3
      with:
          repository: libxposed/api
          path: libxposed/api

    - name: Checkout libxposed/api
      uses: actions/checkout@v3
      with:
          repository: libxposed/service
          path: libxposed/service
        
    - name: permission for sh
      run: chmod +x InstallServiceAndApi.sh
    
    - name: Install Service and Api
      run: ./InstallServiceAndApi.sh

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
