name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout libxposed/api
      uses: actions/checkout@v3
      with:
          repository: libxposed/api
          path: libxposed/api

    - name: Checkout libxposed/api
      uses: actions/checkout@v3
      with:
          repository: libxposed/service
          path: libxposed/service

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build dependencies
      working-directory: libxposed
      run: |
          ./gradlew
          cd api
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew :api:publishApiPublicationToMavenLocal
          cd ..
          cd service
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew :interface:publishInterfacePublicationToMavenLocal
          cd ..
          ./gradlew build
